#common:
model_name: "myconvnet"
run_label: "run_1"
log_freq: 500
seed: 1234
mixed_precision: false

#dataset / data augmentation
dataset:
    root_dir: "/mnt/chenziwen/Datasets/images"
    txt_path: "/mnt/chenziwen/cv/capreg/label_watch.txt"
#    root_dir: "/mnt/chenziwen/Datasets/dc/train"
#    txt_path: "/mnt/chenziwen/Datasets/dc/label.txt"
    category: "classification"
    train_batch_size: 256
    val_batch_size: 256
    eval_batch_size: 256
    dataset_method: 'base'      # base, jpeg4py, turbo
    workers: 8
    persistent_workers: false
    pin_memory: true
    #       color_jitter
    brightness: 0.4
    contrast: 0.4
    saturation: 0.2
    hue: 0.1
    #           Mixup params
    mixup: 0.8    # 'mixup alpha, mixup enabled if > 0. (default: 0.8)'
    cutmix: 1.0   # 'cutmix alpha, cutmix enabled if > 0. (default: 1.0)'
    #           Random Erase params
    reprob: 0.25
    remode: "pixel"
    recount: 1
    #       sampler:
    sampler_name: "batch_sampler"
    width: 256
    height: 256
    smoothing: 0.1    # Label smoothing (default: 0.1)
    interpolation: "bicubic"    # Training interpolation (random, bilinear, bicubic default: "bicubic")

#save model
output_dir: '/mnt/chenziwen/cv/capreg/checkpoints'

#Learning rate schedule parameters
sched: "cosine"
lr: 0.001
epochs: 50
cooldown_epochs: 2
warmup_epochs: 0
warmup_lr: 0.000001
min_lr: 0.00001
decay_rate: 0.1

#Optimizer parameters
optimizer: "adamw"
momentum: 0.9
weight_decay: 0.05

#model:
model:
    num_classes: 2
    finetune: false
    #   layer:
    global_pool: "mean"
    conv_init: "kaiming_normal"
    linear_init: "trunc_normal"
    linear_init_std_dev: 0.02

#ddp:
device_type: "cuda"    # cpu, cuda
cuda_device: [0]    # [0, 1, 2, 3]
enable: false
rank: 0
world_size: -1
dist_port: 30786

#stats:
stats_name: [ "loss", "top1", "top5" ]
checkpoint_metric: "top1"
checkpoint_metric_max: true